// @ts-ignore
import { Request, Response } from 'express';

export default {
  'POST /test/listResult': (req: Request, res: Response) => {
    res.status(200).send({
      success: true,
      code: '正好土入件满地别电争格局图立一式造。',
      message: '安内研往们细看产整文米观龙做识张程。',
      data: [
        {
          id: 82,
          name: '梁秀兰',
          sex: false,
          age: 70,
          createDateTime: '2014-09-14 13:47:32',
          createDate: '1996-04-03',
          createTime: { hour: 84, minute: 93, second: 87, nano: 86 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 71,
          name: '尹丽',
          sex: true,
          age: 63,
          createDateTime: '1989-01-16 08:13:22',
          createDate: '2007-09-02',
          createTime: { hour: 89, minute: 88, second: 66, nano: 92 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 87,
          name: '黎勇',
          sex: false,
          age: 66,
          createDateTime: '1983-11-07 10:53:11',
          createDate: '1991-02-01',
          createTime: { hour: 81, minute: 99, second: 99, nano: 63 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 72,
          name: '吴明',
          sex: false,
          age: 74,
          createDateTime: '2007-02-25 16:45:42',
          createDate: '1975-11-26',
          createTime: { hour: 91, minute: 72, second: 62, nano: 87 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 92,
          name: '江秀兰',
          sex: false,
          age: 66,
          createDateTime: '2003-10-02 13:05:03',
          createDate: '1985-07-08',
          createTime: { hour: 86, minute: 91, second: 80, nano: 73 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 92,
          name: '唐娜',
          sex: true,
          age: 93,
          createDateTime: '2008-10-02 23:43:18',
          createDate: '1984-10-23',
          createTime: { hour: 86, minute: 94, second: 62, nano: 100 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 78,
          name: '锺霞',
          sex: true,
          age: 81,
          createDateTime: '2023-06-02 01:05:37',
          createDate: '2023-04-26',
          createTime: { hour: 69, minute: 61, second: 72, nano: 93 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 70,
          name: '汤超',
          sex: true,
          age: 98,
          createDateTime: '2012-12-04 23:29:27',
          createDate: '1993-09-13',
          createTime: { hour: 73, minute: 76, second: 99, nano: 83 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 83,
          name: '蔡艳',
          sex: false,
          age: 94,
          createDateTime: '1970-09-30 11:25:32',
          createDate: '1992-12-06',
          createTime: { hour: 72, minute: 74, second: 81, nano: 60 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
      ],
    });
  },
};
