// @ts-ignore
import { Request, Response } from 'express';

export default {
  'POST /test/listResult': (req: Request, res: Response) => {
    res.status(200).send({
      success: true,
      code: '际亲集们育他广片意主生车京反后。',
      message: '平名全快料价体流始断林广温强。',
      data: [
        {
          id: 83,
          name: '孙刚',
          sex: false,
          age: 95,
          createDateTime: '1981-04-05 13:58:34',
          createDate: '2005-05-18',
          createTime: { hour: 76, minute: 88, second: 90, nano: 86 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 93,
          name: '方霞',
          sex: true,
          age: 98,
          createDateTime: '2003-07-18 17:43:23',
          createDate: '2022-10-07',
          createTime: { hour: 70, minute: 88, second: 67, nano: 99 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 73,
          name: '江磊',
          sex: false,
          age: 77,
          createDateTime: '1996-09-06 04:03:17',
          createDate: '2012-06-07',
          createTime: { hour: 90, minute: 99, second: 76, nano: 73 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 66,
          name: '郝洋',
          sex: true,
          age: 79,
          createDateTime: '2023-10-24 11:20:12',
          createDate: '2005-10-10',
          createTime: { hour: 98, minute: 66, second: 99, nano: 68 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 92,
          name: '熊敏',
          sex: false,
          age: 61,
          createDateTime: '2007-10-07 01:15:10',
          createDate: '1992-01-13',
          createTime: { hour: 73, minute: 71, second: 82, nano: 88 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 99,
          name: '金艳',
          sex: true,
          age: 94,
          createDateTime: '1999-12-08 12:26:07',
          createDate: '1977-01-11',
          createTime: { hour: 71, minute: 72, second: 88, nano: 79 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 75,
          name: '丁敏',
          sex: true,
          age: 76,
          createDateTime: '2002-07-18 14:51:30',
          createDate: '2000-03-15',
          createTime: { hour: 89, minute: 77, second: 96, nano: 74 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
        {
          id: 96,
          name: '姚刚',
          sex: false,
          age: 71,
          createDateTime: '1984-12-20 07:19:08',
          createDate: '2018-05-08',
          createTime: { hour: 91, minute: 75, second: 97, nano: 90 },
          statusEnum: 'ENABLE',
          statusEnum2: 'ENABLE',
        },
      ],
    });
  },
};
