// @ts-ignore
import { Request, Response } from 'express';

export default {
  'POST /test/pageResult': (req: Request, res: Response) => {
    res.status(200).send({
      success: false,
      code: '红消比山委求易时历一商林算。',
      message: '影或样战式革得定都选照主改。',
      data: {
        page: 84,
        total: 89,
        list: [
          {
            id: 65,
            name: '叶涛',
            sex: false,
            age: 73,
            createDateTime: '1980-04-09 09:35:46',
            createDate: '1974-11-02',
            createTime: { hour: 100, minute: 70, second: 64, nano: 74 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 80,
            name: '乔娜',
            sex: true,
            age: 84,
            createDateTime: '1975-11-21 03:58:36',
            createDate: '2016-07-21',
            createTime: { hour: 93, minute: 92, second: 89, nano: 84 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 97,
            name: '文秀兰',
            sex: false,
            age: 61,
            createDateTime: '2010-02-04 12:45:44',
            createDate: '2008-10-29',
            createTime: { hour: 94, minute: 93, second: 96, nano: 76 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 82,
            name: '王娜',
            sex: false,
            age: 72,
            createDateTime: '1986-08-21 11:46:46',
            createDate: '1988-09-24',
            createTime: { hour: 84, minute: 62, second: 88, nano: 64 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 77,
            name: '吴明',
            sex: false,
            age: 90,
            createDateTime: '2009-08-26 17:12:25',
            createDate: '1972-02-28',
            createTime: { hour: 64, minute: 86, second: 63, nano: 68 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 78,
            name: '卢静',
            sex: false,
            age: 95,
            createDateTime: '2021-07-07 17:21:47',
            createDate: '2018-10-01',
            createTime: { hour: 72, minute: 98, second: 70, nano: 60 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 86,
            name: '孔军',
            sex: false,
            age: 60,
            createDateTime: '2008-01-24 21:07:07',
            createDate: '1989-09-21',
            createTime: { hour: 82, minute: 84, second: 97, nano: 89 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 91,
            name: '蒋敏',
            sex: false,
            age: 82,
            createDateTime: '2005-02-10 22:25:45',
            createDate: '2015-04-13',
            createTime: { hour: 84, minute: 90, second: 78, nano: 99 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 81,
            name: '姜强',
            sex: false,
            age: 84,
            createDateTime: '2005-04-15 08:50:22',
            createDate: '1990-11-26',
            createTime: { hour: 84, minute: 66, second: 97, nano: 79 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 72,
            name: '魏洋',
            sex: false,
            age: 66,
            createDateTime: '2023-07-09 08:55:10',
            createDate: '1999-11-16',
            createTime: { hour: 78, minute: 87, second: 84, nano: 64 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 95,
            name: '邵超',
            sex: false,
            age: 69,
            createDateTime: '2000-07-26 11:00:24',
            createDate: '2000-03-05',
            createTime: { hour: 84, minute: 79, second: 84, nano: 78 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 63,
            name: '孔娟',
            sex: false,
            age: 63,
            createDateTime: '1984-03-12 10:41:52',
            createDate: '1991-05-06',
            createTime: { hour: 68, minute: 92, second: 70, nano: 61 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 64,
            name: '孙娟',
            sex: true,
            age: 76,
            createDateTime: '2006-05-27 10:33:28',
            createDate: '2020-04-04',
            createTime: { hour: 61, minute: 96, second: 91, nano: 98 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 78,
            name: '马超',
            sex: false,
            age: 84,
            createDateTime: '1991-07-06 03:25:00',
            createDate: '1989-09-08',
            createTime: { hour: 73, minute: 77, second: 73, nano: 61 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 95,
            name: '董勇',
            sex: false,
            age: 61,
            createDateTime: '1976-10-12 20:14:19',
            createDate: '2020-06-22',
            createTime: { hour: 66, minute: 81, second: 69, nano: 73 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
        ],
      },
    });
  },
};
