// @ts-ignore
import { Request, Response } from 'express';

export default {
  'POST /test/pageResult': (req: Request, res: Response) => {
    res.status(200).send({
      success: false,
      code: '反运满国强她主感响转识作可。',
      message: '般立是青线成美记动第属时圆。',
      data: {
        page: 68,
        total: 89,
        list: [
          {
            id: 76,
            name: '黄平',
            sex: false,
            age: 77,
            createDateTime: '2004-08-14 21:44:32',
            createDate: '1980-05-18',
            createTime: { hour: 64, minute: 88, second: 75, nano: 64 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 100,
            name: '谢洋',
            sex: true,
            age: 76,
            createDateTime: '2001-09-06 08:10:55',
            createDate: '2007-11-29',
            createTime: { hour: 74, minute: 98, second: 69, nano: 72 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 69,
            name: '潘娟',
            sex: true,
            age: 98,
            createDateTime: '2013-09-15 15:56:56',
            createDate: '2018-04-28',
            createTime: { hour: 65, minute: 77, second: 97, nano: 89 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 99,
            name: '孔艳',
            sex: true,
            age: 73,
            createDateTime: '1974-11-20 04:23:28',
            createDate: '1981-12-28',
            createTime: { hour: 74, minute: 80, second: 72, nano: 78 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 77,
            name: '蒋平',
            sex: true,
            age: 79,
            createDateTime: '2012-03-31 05:16:22',
            createDate: '2012-11-16',
            createTime: { hour: 92, minute: 82, second: 78, nano: 84 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 86,
            name: '余芳',
            sex: true,
            age: 96,
            createDateTime: '1992-05-16 15:58:56',
            createDate: '1983-07-06',
            createTime: { hour: 100, minute: 99, second: 89, nano: 66 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 84,
            name: '萧娜',
            sex: true,
            age: 93,
            createDateTime: '1989-12-13 10:15:19',
            createDate: '2004-08-01',
            createTime: { hour: 61, minute: 85, second: 84, nano: 92 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 66,
            name: '潘强',
            sex: false,
            age: 60,
            createDateTime: '2001-10-25 15:36:22',
            createDate: '2004-11-30',
            createTime: { hour: 69, minute: 97, second: 96, nano: 76 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 98,
            name: '汤敏',
            sex: true,
            age: 91,
            createDateTime: '1971-02-10 09:11:48',
            createDate: '2010-09-19',
            createTime: { hour: 82, minute: 62, second: 98, nano: 63 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 89,
            name: '史艳',
            sex: true,
            age: 64,
            createDateTime: '2022-12-20 11:06:34',
            createDate: '2020-02-29',
            createTime: { hour: 96, minute: 72, second: 77, nano: 81 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
          {
            id: 98,
            name: '方杰',
            sex: true,
            age: 89,
            createDateTime: '1971-09-09 07:20:25',
            createDate: '1993-01-20',
            createTime: { hour: 68, minute: 68, second: 100, nano: 82 },
            statusEnum: 'ENABLE',
            statusEnum2: 'ENABLE',
          },
        ],
      },
    });
  },
};
